experiment:
    project: "unilip_stage1"
    name: "unilip_stage1_run1"
    output_dir: "unilip_stage1_run1"
    max_train_examples: 40_000_000
    save_every: 25_000
    eval_every: 25_000
    generate_every: 5_000
    log_every: 50
    log_grad_norm_every: 1_000
    resume: True
    init_weight: ""


model:
    name: DC_AE_ViT_Stage2_448_Checkpoint
    embed_dim: 32
    patch_size: 14
    stage1_ckpt: 2B_stage2/checkpoint-xxx/ema_model/pytorch_model.bin
    mllm_path: OpenGVLab/InternVL3-2B
    dc_ae_path: mit-han-lab/dc-ae-f32c32-sana-1.1-diffusers
    vq_model:
        quantize_mode: vae
        finetune_decoder: False

losses:
    name: ReconstructionLoss_Stage2
    discriminator_start: 0
    quantizer_weight: 1.0
    discriminator_factor: 1.0
    discriminator_weight: 0.1
    perceptual_loss: "lpips-convnext_s-1.0-0.1"
    perceptual_weight: 1.1
    distill_loss: OpenGVLab/InternVL3-2B
    distill_weight: 1.0
    reconstruction_loss: "l2"
    reconstruction_weight: 1.0
    lecam_regularization_weight: 0.001
    kl_weight: 0.0
    logvar_init: 0.0

dataset:
    params:
        train_shards_path_or_url: ["BLIP3o-Pretrain/BLIP3o-Pretrain-Short-Caption/*.tar", "BLIP3o-Pretrain/BLIP3o-Pretrain-Long-Caption/*.tar", "BLIP3o-Pretrain/BLIP3o-Pretrain-JourneyDB/*.tar"]
        sample_ratio: [0.2, 0.6, 0.2]
        eval_shards_path_or_url: "imagenet_sharded/val/imagenet-val-{000000..000049}.tar"
        num_workers_per_gpu: 12
        dataset_with_class_label: False
        dataset_with_text_label: True
    preprocessing:
        resize_shorter_edge: 448
        crop_size: 448
        random_crop: True
        random_flip: True
        normalize_mean: [0.485, 0.456, 0.406]
        normalize_std: [0.229, 0.224, 0.225]
        imagenet_norm: True


optimizer:
    name: adamw 
    params:
        learning_rate: 1e-4
        discriminator_learning_rate: 1e-4
        beta1: 0.9
        beta2: 0.999
        weight_decay: 1e-4

lr_scheduler:
    scheduler: "cosine"
    params:
        learning_rate: ${optimizer.params.learning_rate}
        warmup_steps: 10_000
        end_lr: 1e-5

training:
    gradient_accumulation_steps: 1
    per_gpu_batch_size: 32
    mixed_precision: "bf16"
    enable_tf32: True
    enable_wandb: True
    use_ema: True
    seed: 42
    max_train_steps: 100_000
    num_generated_images: 2
    max_grad_norm: 1.0